name: Build and Push Docker Image

on:
  push:
    branches:
      - build  # Hoặc tên nhánh mà bạn muốn trigger (ví dụ: master hoặc develop)
  pull_request:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout mã nguồn từ GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: xuanhoangg2004
        password: 8aKJuE32kzUF!Dk
    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t xuanhoangg2004/techschool-fpoly:frontend .

    # Push Docker image lên Docker Hub
    - name: Push Docker image
      run: |
        docker push xuanhoangg2004/techschool-fpoly:frontend
